import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.scss";
import { Header } from "@/components/molecules/header/Header";
import { Footer } from "@/components/molecules/footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            minHeight: "100vh",
            position: "relative",
          }}
        >
          <Header />
          <div
            style={{
              position: "absolute",
              top: 0,
              left: 0,
              width: "100%",
              height: "100%",
              zIndex: -1,
            }}
          >
            <video
              autoPlay
              muted
              loop
              playsInline
              id="bg-video"
              style={{ width: "100%", height: "100%", objectFit: "cover" }}
            >
              <source
                src="/images/7219773-uhd_3840_2160_25fps.mp4"
                type="video/mp4"
              />
            </video>
          </div>
          <main style={{ flex: 1, zIndex: 1 }}>{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
